name: ci

on:
  push:
    tags: 
      - '*'

jobs:
  steps:
    - uses: actions/checkout@v1.0
      name: Check out code

    - uses: mr-smithers-excellent/docker-build-push@v3
      name: Build & push Docker image
      with:
        image: lelandsindt/siotwt
        registry: docker.io 
        username: lelandsindt 
        password: ${{ secrets.DOCKERHUB_TOKEN }}

